version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  filebeat:
    build:
        context: ./filebeat
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    volumes:
        - ./elk-express-ts-monitoring-logs:/src/logs
    depends_on:
        - elasticsearch
        - kibana

  elk-express-ts-monitoring:
    build:
      context: ./elk-express-ts-monitoring
      dockerfile: Dockerfile
    container_name: elk-express-ts-monitoring
    ports:
      - "3001:3001"
    depends_on:
      - elasticsearch
    volumes:
        - ./elk-express-ts-monitoring-logs:/src/logs

volumes:
    elasticsearch_data:
        driver: local